### ISSUE TITLE
db연결 오류

### ISSUE THREAD

**Issue by JangKroed** [JangKroed/wanted-pre-onboarding-backend#3]
```
/Users/e3ts_dev/Desktop/wanted-pre-onboarding-backend/node_modules/sequelize/lib/model.js:666
    options = Utils.merge(_.cloneDeep(globalOptions.define), options);
                                                    ^

TypeError: Cannot read properties of undefined (reading 'define')
    at Users.init (/Users/e3ts_dev/Desktop/wanted-pre-onboarding-backend/node_modules/sequelize/lib/model.js:666:53)
    at Object.<anonymous> (/Users/e3ts_dev/Desktop/wanted-pre-onboarding-backend/src/db/models/users.js:14:7)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/e3ts_dev/Desktop/wanted-pre-onboarding-backend/src/db/models/index.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.16.1
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by JangKroed** [comment]
type: module 추가 및 적용 이후 경로 재설정으로 해결.
